### ISSUE TITLE
Beautify GUI to accommodate >1 Modules and/or >1 Tags

### ISSUE THREAD

**Issue by IsabelChong** [AY2223S2-CS2103T-T15-4/tp#104]
When there are 2 tags for `2. Benson`, and 2 modules for `5. Elle`, there is a GUI bug as seen on the left pane.

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/71481877/227118584-4c045e46-fb95-4e82-bb2d-382eaec9781c.png">

Let's make it consistent to the current expected GUI.
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/71481877/227118994-8114fbc6-2000-4f8a-9efd-7fd101ace619.png">

**Comment by afiqzu** [comment]
Issue is not applicable anymore as student card now only contains student name and student ID
