### ISSUE TITLE
Allow finding student by studentID

### ISSUE THREAD

**Issue by afiqzu** [AY2223S2-CS2103T-T15-4/tp#105]
Since students with duplicate studentIDs cannot be added to to CLIpboard, it will be nice to know who that existing student is by finding them by their studentID
<img width="588" alt="Screenshot 2023-03-23 at 9 31 58 PM" src="https://user-images.githubusercontent.com/93078202/227220054-c99946ee-f916-4cac-b44c-01c3a66452d1.png">
^ Error message shown as there is already a student with studentID of A0123456X in CLIpboard

**Comment by swxk19** [comment]
Note to whoever implements this:
Haven't tested this, but I believe duplicate studentIds can actually be added, if they're added to different groups. 
if you decide to implement `find` command to be able to be called from any page, e.g. `find` while in `course` page, be aware that it is possible for `find <sid>` to give multiple results in our current implementation (as of 27/3)
