### ISSUE TITLE
Remodel Notes (Copied from PR)

### ISSUE THREAD

**Issue by swxk19** [AY2223S2-CS2103T-T15-4/tp#109]
For adding sessions/assignment, you can refer to `logic/commands/addCommand/AddGroupCommand`. Make sure to have a look at how AddCommandParser works now too. 
For storage methods, can refer to my classes in `storage/serializedClasses`. Mostly can copy paste for your own classes, just modify the referencing.

## What you can do now
Suppose we have this in the data file.
```
{
  "courses" : [ {
    "courseCode" : "1",
    "groups" : [ ]
  }, {
    "courseCode" : "2",
    "groups" : [ ]
  } ]
}
```
this data means: there are currently 2 courses, both of which do not have any groups or students yet.

When you start the app, you will be on the `COURSES` page. GUI doesnt support this, so you just have to imagine :-).
On the bright note, storage functions are implemented, so you can sort of "navigate" by looking at the data file. You can kinda treat it as the "ListPanel", just that you cant see what you've selected.

note: you should only call `add course` if you are on the COURSE page, `add group` only if you are on the GROUP page, so on so forth..

you can call `add course <coursename>`, or
you can call `select 2` to select course #2. This will bring you to the `GROUPS` page.
Since there are no groups yet, you can `add group <groupname>`
Then similarly, you can call `select 1` to navigate to the group you just created. This brings you to the `STUDENTS` page.
As per the dummy data, there are no students yet, so you have to call `add student n/ p/ e/ ......` (NOTE: module is no longer a part of student. U will get runtime error if u input )

## Notable Design Changes
1. AddCommand is now an abstract class, as it is generalisable to add different things, Course, Student, Group etc. (adding attendance / assignemnts can also share this command, up to your choice)
2. "Module" should be referred to "Course" instead, i encountered some clashes as Module is a native class in Java, can be easily prone to error if not careful. I've changed as much variables names accordingly that I've encountered
3. Module field not used in student (~~still present there, but won't be referenced~~ **commented out reference**). since to navigate to the student in the first place you need to start from the module.
4. Student only attached to one module now. Tentatively, to avoid design complexity. 
5. View command is obsolete, replaced by `select <index>` - need to change UI handling for "view"
6. I implemented my own Json saving classes, because the AB3 one is damn wild (i got stuck for 1hr+ tryna unds still no clue). So you can ignore the files in /storage that are named like "JsonAdapted...". Those are now unused. If you want to refer to my implementation, its under storage/serializedClasses/. Another important class for storage is JsonRosterStorage. This one is from AB3 but i still use some portion of it. 
7. Information about the current page you are on is stored in `logic/CurrentSelection`. It contains fields for course, group, student, and an enum to indicate the current page. The fields for course/group/student are for storing what the user has selected via `select` command, since the main form of navigation is only by `select`. This allows you to perform some "filtering" by looking at these fields.
8. If you want to see how navigation is handled, you can look at commands/SelectCommand

## Issues you will very probably face
1. ~~No back navigation yet. Have to restart app once you navigate down.~~ **Added**
2.  Some ~~No~~ restriction of commands based on current page. You will have run-time error if you input command in 
the wrong state. Remember to call the select command to navigate between pages.
3. Can now handle incorrect json format or missing file  ~~Storage saving/loading does not have any validation checks.
if you have problems with storage, recreate the datafile. Same name `addressbook.json`.
you can use the dummy data above to populate it, because I'm not sure how it behaves with empty data file. Personally I havent faced any issues with saving/loading when the file is properly initialised. ~~
4. ~~Testing has literally not been touched. It will likely just fail compilation.~~ **Fixed compile errors (will compile, but probably wont pass test case)**
5. Commands we implemented previously likely need big changes. I'll try to work on this for yall cuz the navigation might make it work quite differently.
6. SampleDataUtil dummy data needs remodelling to fit new design
7. Incorrect error messages or incorrect reply to user. I was focusing more on logic and didnt pay much attention to writing strings
8. Redundant UniqueStudentList field in ModelManager. All referencing for studentLists must now be navigated through the courseList(also in ModelManager) first. Im afraid to remove it for now because i think its intertwined in many places.

## Things that are simpler to implement if you want to
1.  Most of my work are quite compartmentalised away from the UI, so it's likely still familiar for you to work with.
2. LogicManager is the class that holds information about the current page (a field called CurrentSelected). LogicManager is also directly accessible from UI, so if you want to implement some navigation hadnling for the UI i think should be doable.

## Commands remodel progress
- [x] add
- [ ] clear
- [x] exit
- [x] help
- [x] list (may be obsolete)
- [x] module (may be obsolete)
- [x] view (may be obsolete)
- [x] delete
- [x] edit
- [x] find
- [x] remark
- [ ] sort
- [x] select
- [ ] undo
- [x] upload

**Comment by tyx021** [comment]
edit command fixed in #126
