### ISSUE TITLE
Update User Guide with changes from remodelling

### ISSUE THREAD

**Issue by peaol** [AY2223S2-CS2103T-T15-4/tp#129]
- Replace screenshots of our old Ui with the new ones
- Reorganise commands based on its page (Course, Group, Session, Student, etc)
- Update UG with the newly added commands

- [x] Initial mass update (#128)
- [x] Update with `assign` command and `Task` commands and its pages (Handled in #135)
- [x] fixing broken commands such as find, view
- [x] adding screenshots of new gui with session and task tab

**Comment by tyx021** [comment]
Note: commands included in UG but are currently broken, to be checked after done fixing
- find
- remark
- upload
- sort
- undo
- clear
