### ISSUE TITLE
Restrict format for `attendance` command

### ISSUE THREAD

**Issue by tyx021** [AY2223S2-CS2103T-T15-4/tp#147]
Expected: `attendance` command only works when user types exactly same format (i.e. `attendance`)

Actual: Did not check for extra arguments
`attendance 1`, `attendance 1,2,3`, `attendance 1 2 3` works the same as `attendance`

**Comment by swxk19** [comment]
To mention in UG that extra args are ignored

**Comment by tyx021** [comment]
Mentioned in #228
