### ISSUE TITLE
[PE-D][Tester A] Cannot return to showing the whole list of students after using "find student" command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T15-4/tp#179]
After calling ```find student``` command in the Students page, there seems to be no way to get back to seeing the whole list again.

![SCR-20230331-kel.png](https://raw.githubusercontent.com/fahim-tazz/ped/main/files/acc69ee1-641f-49cd-b032-ccd6b74a3c70.png)SCR-20230331-kel.png

```find student``` correctly returns results.

![SCR-20230331-kf7.png](https://raw.githubusercontent.com/fahim-tazz/ped/main/files/baf5464c-69f0-4dd5-82db-4bec0e712a8a.png)SCR-20230331-kf7.png

But to view whole list, user has to use ```back```, then enter that page again.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: fahim-tazz/ped#1

**Comment by tyx021** [comment]
it was originally `list` command, however was removed in v1.3

**Comment by swxk19** [comment]
a simple fix. Can look into how `select` and `back` clears the filteredList's predicate.

**Comment by tyx021** [comment]
> a simple fix. Can look into how `select` and `back` clears the filteredList's predicate.

But is it possible to fix this without adding new command? 🤔

**Comment by tyx021** [comment]
Can't fix in v1.4. Alternative is by `undo` command. (To be added into UG)
