### ISSUE TITLE
[PE-D][Tester C] Cannot see full task name for very long strings

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T15-4/tp#183]
It is good that the UI automatically truncates very long strings, but there should also be a way to view the full string if possible

![Screenshot 2023-03-31 at 2.48.31 PM.png](https://raw.githubusercontent.com/jereldlimjy/ped/main/files/daa3da88-9338-4dfd-9323-90ccfefc2220.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: jereldlimjy/ped#4

**Comment by tyx021** [comment]
Closed as mentioned under #206

**Comment by tyx021** [comment]
Nice to fix

**Comment by swxk19** [comment]
Not possible to fix this with limits, because resizing the window will also vary the truncation length. 
Will have to solve on UI side.

Alternative fixes:
1. "Click to expand" 
2. Show full text when mouse hovers over it
3. Text wrapping (might clog up UI)
4. Ignore this issue

**Comment by tyx021** [comment]
![image](https://user-images.githubusercontent.com/97380048/229989766-18d369e1-313b-4b81-ac5c-f1ae94db6bd6.png)
(from: [here ](https://nus-cs2103-ay2223s2.github.io/website/schedule/week12/project.html#:~:text=On%20the%20tutorial%20day%2C%20one%20member%20should%20post%20a%20message%20in%20your%20team%27s%20MS%2DTeams%20channel))
Maybe we will just add it to "future enhancement"

**Comment by afiqzu** [comment]
Updated DG in #265,
Left UG update
