### ISSUE TITLE
[PE-D][Tester C] Allow copying of more things

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T15-4/tp#193]
Is there a reason why `copy` is targeted only at a student's email?

![Screenshot 2023-03-31 at 3.01.11 PM.png](https://raw.githubusercontent.com/jereldlimjy/ped/main/files/65592a09-5125-4014-88fd-415090ae9d1b.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: jereldlimjy/ped#6

**Comment by swxk19** [comment]
Agree that it can be generalised, but is a feature extension rather than a bug. Can consider changing this once we've cleared actual bugs

**Comment by tyx021** [comment]
can't be fixed in v1.4
