### ISSUE TITLE
[PE-D][Tester A] Upload command does not need Absolute Path

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T15-4/tp#199]
According to the UG, ```upload``` profile picture command strictly requires Absolute Path.

![image.png](https://raw.githubusercontent.com/fahim-tazz/ped/main/files/54e1a4ab-c893-479f-907d-a6a47275d101.png)

Entering Relative path also works with errors.

![image.png](https://raw.githubusercontent.com/fahim-tazz/ped/main/files/90cd2cd5-b65a-43a3-bfc8-38ab20e9ee42.png)

It may be smarter to remove the constraint from the UG, since the feature already works on your software.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: fahim-tazz/ped#5

**Comment by tyx021** [comment]
Explanation needs to be added to UG
**also the meaning of absolute path & relative path
