### ISSUE TITLE
Runtime error for edit student

### ISSUE THREAD

**Issue by tyx021** [AY2223S2-CS2103T-T15-4/tp#204]
`ArrayIndexOutofBoundError `caused by the three lines, in `MainWindow::refreshViewPane()`, might need @afiqzu to look into it

![image](https://user-images.githubusercontent.com/97380048/229262707-77614f57-6961-4391-9bf0-87f08a34d30a.png)

**Comment by swxk19** [comment]
I encountered this too but didn't see any functionality issue visually. Did you see if this affected anything?

**Comment by tyx021** [comment]
It doesn't affect anything on my side as well, but we should still prevent runtime error from happening 🤔

**Comment by tyx021** [comment]
I encountered this again by doing `select 1` twice from home page, the error arise at the same line.
Again, command still works fine, but the command will not be cleared after I press enter.

https://user-images.githubusercontent.com/97380048/229570315-d13ee889-c49e-43cd-a434-a106d7234f5f.mp4

**Comment by tyx021** [comment]
This seems to be caused by not checking if `viewedStudent.size() == 0`, the error goes away once I add an if statement to check for such case, however still need to observe if there's any more bug.
