### ISSUE TITLE
Checking for valid student id in `find student` by sid, but not in `add student`

### ISSUE THREAD

**Issue by tyx021** [AY2223S2-CS2103T-T15-4/tp#232]
I can add student with student id A123, but can't find the student with `find student A123`

![image](https://user-images.githubusercontent.com/97380048/230323848-9a44f6b6-f930-4316-ae2b-cabe667427a6.png)

![image](https://user-images.githubusercontent.com/97380048/230323928-71d20c9c-5382-4eaa-b0e9-124da1434580.png)

**Comment by IsabelChong** [comment]
Also tried this and it seems like `find student` by student id only works with 7 characters and above, eg `7777777`, 'A222222'

Will update `StudentParticularsContainsPredicate` class in a later linked PR
<img width="848" alt="image" src="https://user-images.githubusercontent.com/71481877/230552367-aea4cda7-fa34-405e-ad27-07dbfb49594f.png">

**Comment by tyx021** [comment]
I fixed this by just checking if a student' sid / name contains keyword as substring, need to update in UG.

As for now, `find student A123`  will return the following result.
![image](https://user-images.githubusercontent.com/97380048/230570001-f4c80c31-ed78-4e55-b356-45315927a851.png)
