### ISSUE TITLE
Refactor AB3 code to suit CLIpboard

### ISSUE THREAD

**Issue by afiqzu** [AY2223S2-CS2103T-T15-4/tp#39]
Currently, variable and class names in AB3 such as 'Person' class are not applicable to CLIpboard.

Let's change these names to better suit CLIpboard.

Possible renaming changes:
'Address book' -> 'Student Roster'
'address' field in Person -> 'studentId'

### Remaining tasks (non-exhaustive):
- [ ] Rename json files used in testing (see #53)
- [ ] Most variable names have been changed, but some might have been missed. Keep a lookout.

**Comment by swxk19** [comment]
finally! :D
