### ISSUE TITLE
General Testing Issues

### ISSUE THREAD

**Issue by swxk19** [AY2223S2-CS2103T-T15-4/tp#46]
## (Add on to this checklist)

- [x] Add testing for `view` command
- [x] Add testing for `remark` command
- [x] Update testing for `add` command
- [x] Update testing for `edit` command
- [x] Update testing for `EditCommandParser`
- [x] Add testing for 'upload' command
- [x] #53 

## Smoke-Tests: 
Update these when our product is finalized.
- [x] Runnable on Windows (as of commit: 14f0194b3af351b93cdf9c57e84e7d552a28a851)
- [x] Runnable on MacOS (as of commit: 14f0194b3af351b93cdf9c57e84e7d552a28a851)
- [x] Runnable on Linux (as of commit: 14f0194b3af351b93cdf9c57e84e7d552a28a851)

**Comment by tyx021** [comment]
Tested on Windows and works as expected 👍
