### ISSUE TITLE
General Documentation Issues

### ISSUE THREAD

**Issue by swxk19** [AY2223S2-CS2103T-T15-4/tp#63]
# This list is not exhaustive, please add on to it if you encounter any additional issues
Requirements as per Week 7:
[DG](https://nus-cs2103-ay2223s2.github.io/website/schedule/week7/project.html#5-update-the-dg-user-stories-glossary-nfrs-use-cases) 
[UG](https://nus-cs2103-ay2223s2.github.io/website/schedule/week7/project.html#3-update-the-ug)

[Link to CLIpboard Guides](https://ay2223s2-cs2103t-t15-4.github.io/tp/)

Would be better to categorise these according to the respective document they would affect. But no time for now :-)

---

### Landing Page
- [x] Missing link to UG in header
Original:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/45385178/224688557-5fedb84a-3078-408a-bc97-3c751cd1fb3e.png">
Current:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/45385178/224688450-c25f7208-fb5d-41aa-9841-ec758cf847ce.png">

--- 
### User Guide
- [x] Update docs for newly added/changed commands
1. List of available commands
2. `add` command format changed.
3. `view` command keyword does not match UG (`show`). Either change the UG or change the code
4. Missing upload command

- [x] README, Landing Page & UG: UI mockup does not match actual UI

---
### Developer Guide
- [x] Still references AB3. 
- [x] Landing Page: references AB3 instead of CLIpboard
<img width="414" alt="image" src="https://user-images.githubusercontent.com/45385178/224691966-c680d118-2ac7-4e75-95e6-0018fc522c16.png">
<img width="286" alt="image" src="https://user-images.githubusercontent.com/45385178/224692096-83b8e152-8d90-4696-9e41-0f60b4fd8ad5.png">

- [x] AboutUs: Contact information uses filler email
<img width="345" alt="image" src="https://user-images.githubusercontent.com/45385178/224692582-16073a9b-011f-4c58-80a9-3376ffbd00c5.png">
- [x] DG.Glossary: Student information does not match our implementation
<img width="405" alt="image" src="https://user-images.githubusercontent.com/45385178/224693941-574ba055-07cd-4072-adee-b6cfde1c07f0.png">

---

## Improvements (can be pushed to next iteration instead)

- [x] Landing Page: Header title does not match our product name (is this intended?)
<img width="110" alt="image" src="https://user-images.githubusercontent.com/45385178/224691798-db2045b0-95e7-47ab-949c-070bedc1dc40.png">

- [x] Proof-read UG for v1.2
- [x] Proof-read DG for v1.2
- [x] Apply concepts from CS2101 (Crucial for grading)

**Comment by tyx021** [comment]
Updated README and user guide in #76
