### ISSUE TITLE
As a TA, I want to add new students with their particulars

### ISSUE THREAD

**Issue by swxk19** [AY2223S2-CS2103T-T15-4/tp#7]
.. so that I can create a new profile for a student.

___
Basic `adding` functionality has already been implemented in **AB3**. 
Below are what is to be refactored or added for **CLIpboard**.

- [x] Extend `Module` from `Tag`
- [x] Add `PREFIX_MODULE = m/` prefix and update `AddCommandParser` to use `PREFIX_MODULE` (must have at least one) before `PREFIX_TAG` (zero or more). 
- [x] Update `AddCommand` instructions for `MESSAGE_USAGE` to have `m/` before`t/`
- [x] At least one `module` has to be added (in `AddCommandParser`)
- [ ] Allow adding of `notes` together with adding of student command (Tentative after #21 is merged)
```
Eg. add n/John Doe p/98765432 e/johnd@example.com sid/A1234567X m/CS2103T n/Discussing Topic A on 3 Mar 2023
```

Note that some aspects of `EditCommand` have been changed due to overlaps of the functionality of `modules`.

**Comment by swxk19** [comment]
Might require supplemental feature to upload image for the student.

**Comment by IsabelChong** [comment]
> Might require supplemental feature to upload image for the student.

Moved under #45
